language: python
python:
  - "2.7"

# command to let run a real GUI application or web browser
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
# command to install dependencies
install: "pip install -r requirements.txt"

  
before_script: 
  - "flake8 --ignore=F403 manage.py sched tests/features"
  - "flake8 --max-complexity=5 --ignore=F403 manage.py sched tests/features"

# command to run tests
script: 
  - coverage run --omit="*site-packages*" PU.py
  - coverage report -m
  - nosetests --with-doctest -s filters
  - nosetests --with-doctest -s PRuebaDoctest
  - python manage.py runserver & lettuce tests
